services:
  proxy:
    image: caddy:2.6.4-with-sablier
    ports:
      - "8081:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro

  whoami:
    image: containous/whoami:v1.5.0
    deploy:
      labels:
        - sablier.enable=true
        - sablier.group=demo

  sablier:
    image: acouvreur/sablier:1.4.0
    command:
        - start
        - --provider.name=swarm
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

