name = "gh-issues-next"
compatibility_date = "2023-07-12"

kv_namespaces = [
{ binding = "KV", id = "1ba8b247024c4a769e5a157820764ba4", preview_id = "9714d734a5464f1aaaaa7c0bfd5215fc"  }
]


# the `key = "value"` format
[vars]
SESSION_SECRET="<>"
GITHUB_CLIENT_ID="<>"
GITHUB_REDIRECT_URI="<>"
NEXT_PUBLIC_VERCEL_URL="localhost:8788"
GITHUB_SECRET="<>"
GITHUB_PERSONAL_ACCESS_TOKEN=""
