services:
  proxy:
    image: caddy:2.6.4-with-sablier
    ports:
      - "8082:80"
      - "443:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
  app:
    image: dcr.fredkiss.dev/gh-next:dev
    deploy:
      replicas: 0
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - sablier.enable=true
        - sablier.group=codex_pr_123
  # whoami:
  #   image: containous/whoami:v1.5.0
  #   deploy:
  #     labels:
  #       - sablier.enable=true
  #       - sablier.group=demo

  sablier:
    image: acouvreur/sablier:1.4.0
    command:
        - start
        - --provider.name=swarm
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

