version: "3.4"

services:
  app:
    image: dcr.fredkiss.dev/gh-next:latest
    ports:
      - "8988:3000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
