version: "3.4"

services:
  gh-next-prod:
    image: dcr.fredkiss.dev/gh-next:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - gh-next
networks:
  gh-next:
    external: true
